### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Arakananta** [nicohaenggi/SafariBooks-Downloader#49]
After a few download that working properly, i get this error message every time i try to download.

```
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/lib/cli/index.js:27:28)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

**Comment by hypr2771** [comment]
> After a few download that working properly, i get this error message every time i try to download.
> 
> ```
> undefined:1
> 
> SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/lib/cli/index.js:27:28)
>     at Module._compile (internal/modules/cjs/loader.js:736:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
>     at Module.require (internal/modules/cjs/loader.js:665:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/index.js:11:18)
>     at Module._compile (internal/modules/cjs/loader.js:736:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
>     at executeUserCode (internal/bootstrap/node.js:526:15)
>     at startMainThreadExecution (internal/bootstrap/node.js:439:3)
> ```

Yo mate,
With such little information it's pretty hard to help you.
Would you mind running again with `--debug` flag ?

**Comment by Arakananta** [comment]
> > After a few download that working properly, i get this error message every time i try to download.
> > ```
> > undefined:1
> > 
> > SyntaxError: Unexpected end of JSON input
> >     at JSON.parse (<anonymous>)
> >     at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/lib/cli/index.js:27:28)
> >     at Module._compile (internal/modules/cjs/loader.js:736:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
> >     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
> >     at Module.require (internal/modules/cjs/loader.js:665:17)
> >     at require (internal/modules/cjs/helpers.js:20:18)
> >     at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/index.js:11:18)
> >     at Module._compile (internal/modules/cjs/loader.js:736:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
> >     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
> >     at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
> >     at executeUserCode (internal/bootstrap/node.js:526:15)
> >     at startMainThreadExecution (internal/bootstrap/node.js:439:3)
> > ```
> 
> Yo mate,
> With such little information it's pretty hard to help you.
> Would you mind running again with `--debug` flag ?

**Comment by Arakananta** [comment]
> > After a few download that working properly, i get this error message every time i try to download.
> > ```
> > undefined:1
> > 
> > SyntaxError: Unexpected end of JSON input
> >     at JSON.parse (<anonymous>)
> >     at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/lib/cli/index.js:27:28)
> >     at Module._compile (internal/modules/cjs/loader.js:736:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
> >     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
> >     at Module.require (internal/modules/cjs/loader.js:665:17)
> >     at require (internal/modules/cjs/helpers.js:20:18)
> >     at Object.<anonymous> (/home/user_name/SafariBooks-Downloader/index.js:11:18)
> >     at Module._compile (internal/modules/cjs/loader.js:736:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
> >     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
> >     at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
> >     at executeUserCode (internal/bootstrap/node.js:526:15)
> >     at startMainThreadExecution (internal/bootstrap/node.js:439:3)
> > ```
> 
> Yo mate,
> With such little information it's pretty hard to help you.
> Would you mind running again with `--debug` flag ?

I'm already use the debug and that is the output of my debug.
This is how this happen
- download a few files and everything works properly, then
- download this one file that take a very long time and i open 2 more terminal to download another book
-  that one file failed to download an give me this issue https://github.com/nicohaenggi/SafariBooks-Downloader/issues/34 and the other downloaded successfully and one more the same issue #34 
- i try to redownload again and it gives me this issue.

I'm using ubuntu 18.04 also for additional issue while downloading I'm using Guake, when i try to quit from guake after this issue happen i can't close guake

![ubuntu 18 04 01-2019-01-28-04-12-14](https://user-images.githubusercontent.com/33978908/51806950-fca97d80-22b2-11e9-985d-d7ab23905b23.png)

I already use the downloader from Ubuntu default terminal and it gives me this error as well.

**Comment by hypr2771** [comment]
I see.
Just to make sure, in your screenshot, you did not put any other arguments such as the book ID, I guess it is just in order to illustrate your issue, right?
If so, I'll try to reproduce (I ain't on my personal computer right now 😬) and come back to you.

**Comment by Arakananta** [comment]
> I see.
> Just to make sure, in your screenshot, you did not put any other arguments such as the book ID, I guess it is just in order to illustrate your issue, right?
> If so, I'll try to reproduce (I ain't on my personal computer right now 😬) and come back to you.

The Guake issue is not from the downloader but from the Guake itself i just find out its issue in their code.
